//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UberEats.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Driver
    {
        public int DriverId { get; set; }
        public string DriverFname { get; set; }
        public string DriverLName { get; set; }
        public string DriverEmail { get; set; }
        public string DriverPassword { get; set; }
        public string DriverCellNum { get; set; }
    }
}
