//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UberEats.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int PId { get; set; }
        public string PayCardName { get; set; }
        public string PayCardNum { get; set; }
        public string PayExpDate { get; set; }
        public string PayCvCode { get; set; }
        public int Id { get; set; }
    }
}
