//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UberEats.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Picture
    {
        public int picId { get; set; }
        public byte[] Image { get; set; }
        public Nullable<int> RestaurantId { get; set; }
    }
}
