//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UberEats.models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Core.Objects;
    using System.Data.Entity.Infrastructure;

    public partial class CustomerDbEntities1 : DbContext
    {
        public CustomerDbEntities1()
            : base("name=CustomerDbEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Customer> Customers { get; set; }
        public DbSet<Restaurant> Restaurants { get; set; }
        public DbSet<Admin> Admins { get; set; }
        public DbSet<Picture> Pictures { get; set; }
        public DbSet<Product> Products { get; set; }
        public DbSet<ProdGallery> ProdGalleries { get; set; }
        public DbSet<OrderCopy> OrderCopies { get; set; }
        public DbSet<Payment> Payments { get; set; }
        public DbSet<Order> Orders { get; set; }
        public DbSet<Driver> Drivers { get; set; }
    
        public virtual ObjectResult<GetResInfo_Result> GetResInfo()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetResInfo_Result>("GetResInfo");
        }
    
        public virtual ObjectResult<Procedure_Result> Procedure()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Procedure_Result>("Procedure");
        }
    
        public virtual ObjectResult<GetProductInfo_Result> GetProductInfo()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetProductInfo_Result>("GetProductInfo");
        }
    
        public virtual ObjectResult<Procedure2_Result> Procedure2()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Procedure2_Result>("Procedure2");
        }
    
        public virtual ObjectResult<GetProductInfo1_Result> GetProductInfo1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetProductInfo1_Result>("GetProductInfo1");
        }
    
        public virtual ObjectResult<Procedure21_Result> Procedure21()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Procedure21_Result>("Procedure21");
        }
    
        public virtual ObjectResult<GetProductInfo2_Result> GetProductInfo2()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetProductInfo2_Result>("GetProductInfo2");
        }
    
        public virtual ObjectResult<Procedure22_Result> Procedure22()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Procedure22_Result>("Procedure22");
        }
    
        public virtual ObjectResult<GetOrders_Result> GetOrders()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetOrders_Result>("GetOrders");
        }
    
        public virtual ObjectResult<DriversOrders_Result> DriversOrders()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DriversOrders_Result>("DriversOrders");
        }
    }
}
